### ISSUE TITLE
Cron schedules for alerts

### ISSUE THREAD

**Issue by MerrittJ** [Baselime/cli#2]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I want to create an alert that runs its query at a certain time of day. Currently, I need to wait until that time then set the frequency parameter to '1440' (i.e. minutes in a day) so that it runs once a day, at the time I created the alert.

This is inflexible and doesn't allow for more finely-tuned timings (e.g weekdays only, or less-
regular timing)

### Proposed solution (optional)

Supporting the cron schedule syntax would be more convenient for the above use cases and allow a user to be more specific

**Comment by boristane** [comment]
Thanks for raising this @MerrittJ !

It's been added in this release: https://github.com/Baselime/cli/releases/tag/v0.0.19

You can now submit alerts with a schedule which is a corn job, following the [AWS Specs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions).
