### ISSUE TITLE
At-a-glance, what event(s) triggered my alert?

### ISSUE THREAD

**Issue by MerrittJ** [Baselime/cli#4]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

**Given** I receive an alert from a COUNT query,
**I would like to** see the event(s) that triggered the alert,
**So that** I can quickly triage an issue without navigating away from my channel

Obviously a query may find many events so attaching all of them to the alert may not be feasible...

### Proposed solution (optional)

Perhaps an alert can surface a single field from each event found by its query?

**Comment by boristane** [comment]
Hi Josh! Thanks for the issue.

We shipped a few days a solution to this. When available (on alerts based on a COUNT), we add the most recent event that triggered the alert in the alert body in Slack and in the webhook. 

![screely-1668079557385](https://user-images.githubusercontent.com/10452259/201095332-008a09cf-c80e-48a7-b571-8cd3e3b14509.png)
